config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  #get 'topics/new'
  get 'sessions/new'
  #get 'users/new'
  #get 'pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  #get 'pages/help'
  get "pages/help"

  delete '/topics' , to: 'topics#destroy'
  delete '/comments' , to: 'comments#destroy'
  
  resources :users
  
  get '/login'      , to: 'sessions#new'      #ログインするためのフォームを表示するページを取得
  post '/login'     , to: 'sessions#create'   #新しくｱﾄﾞﾚｽぱパスワード送信してもらいデータを基にセッション作成
  delete '/logout'  , to: 'sessions#destroy'  #ログアウトでセッション削除
  
  #resources :users
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  #post '/comments' , to: 'comments#create'
  #post '/comments' , to: 'comments#new'
  get 'comments/new'
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_content , presence: true
  
  belongs_to :user
  belongs_to :topic
  
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id , presence: true
  validates :description , presence: true
  validates :image , presence: true
  
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  has_many :comments
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true , length: { maximum: 15 }
  EMAIL_RULE = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\Z/
  validates :email, presence: true , format: { with: EMAIL_RULE }
  #validates :password, presence: true
  #validates :password, length: { in: 8..32 }
  PASSWORD_RULE = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[\d])\w{8,32}\Z/
  validates :password, presence: true , format: { with: PASSWORD_RULE}
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics , through: :favorites , source: 'topic'
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user , :logged_in?
  
  def current_user
  @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end
  
  def create
    #binding.pry
    @comment = current_user.comments.new(comment_params)
    #binding.pry
    if @comment.save
      redirect_to topics_path, success: '投稿しました'
    else
      redirect_to topics_path, danger: '失敗しました'
    end
  end
  
  def destroy
    @comment = Comment.find_by(user_id: current_user.id ,topic_id: params[:topic_id])
    #@comment = Comment.find_by(user_id: current_user.id , comment_content: params[:comment_content] , topic_id: params[:topic_id])
    @comment.destroy
    redirect_to topics_path, success: 'コメントを削除しました'
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment_content , :user_id , :topic_id)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入り登録に失敗しました'
    end
  end
  
  def destroy
    #binding.pry
    @favorite = Favorite.find_by(user_id: current_user.id ,  topic_id: params[:topic_id])
    @favorite.destroy
    redirect_to topics_path , success: 'お気に入り登録を取り消しました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    #user = User.find_by(session_params)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path , success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url , info: 'ログアウトしました'
  end
  
  
  private
  def session_params
    params.require(:session).permit(:email , :password)
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
    @comments = Comment.all
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path , success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def destroy
    #@topic = Topic.find_by(user_id: current_user.id)
    @topic = Topic.find_by(user_id: current_user.id , description: params[:description] , image: params[:image])
    @topic.destroy
    redirect_to topics_path, success: '投稿を削除しました'
  end
  
  
  private
  def topic_params
    params.require(:topic).permit(:image , :description)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: "登録が完了しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  #def current_user
    #@current_user ||= User.find_by(id: session[:user_id])
  #end
  
  #def logged_in?
    #!current_user.nil?
  #end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= f.hidden_field :user_id %>
<%= f.hidden_field :topic_id %>

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comments</h1>
        <%= form_for @comment do |f| %>

          <div class="form-group">
            <%= f.label :comment %>
            <%= f.text_area :comment_content, class: 'form-control' %>
          </div>
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class = "top-hero-wrapper text-center">
  <div class = "container top-hero-container">
    <h1 class = "text-white">Make you Happy</h1>
    <h2 class = "text-hwite">Pictgram is a service that you can post photos.</h2>
    
    <h3 class = "text-hwite">heroku確認用_コメント追加</h3>
    
    <div class = "row">
      <div class = "col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn-block btn-white' %>
      </div>
      <div class = "col-md-3">
        <%= link_to 'Log in', login_path , class: 'btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>

            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% else %>
                <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <i class="fas fa-2x fa-heart heart_red"></i>
            <% end %>
            <% end %>
            
            <%= topic.favorite_users.count %>
            
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>

            
            <h5>コメント</h5>
            
              <% @comments.topic.each do |comment| %>
                <p><%= comment.comment_content %></p>
                <%= link_to comments_path(comment.comment_content , topic_id: topic.id), method: :delete do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                <% end %>
              <% end %>
              
            <% @comment = Comment.new unless @comment %>
            
            <%= form_for @comment do |f| %> 
            <div class="form-group">
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :topic_id, :value => topic.id %>
              <%= f.text_area :comment_content, class: 'form-control' %> 
            </div>
            <%= f.submit "投稿", class: 'btn-block' %>
            <% end %>
            
            
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <% if logged_in? %>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path ,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>